### PR TITLE
#7 create column

### PR DESCRIPTION
**Pull request by sLisnychyi**
create header if not exist + tests(integration/unit)

### CODE REVIEW

**Comment by sLisnychyi** [comment]
@vkuchyn please review

**Comment by vkuchyn** [comment]
in #7

**Comment by vkuchyn** [comment]
connect #7

**Comment by vkuchyn** [comment]
@sLisnychyi 
After merging to master - there are test failures:
1. test GdataSpreadSheetReaderUnitTest.findCellByColumn
Pls, do next steps:
1. checkout master
2. make temp branch like git checkout -b temp
3. Merge there your local feature branch 
git merge <feature_branch>
mvn clean install - run build process. Fix all failures (*.p12 should be in resources folder - not outside)

**Comment by sLisnychyi** [comment]
@vkuchyn fixed test and .p12 file

**Comment by vkuchyn** [comment]
@sLisnychyi Thank you for your job. Read my comments and make changes pls. Pay attention on small things - like comment about not used logger was ignored. If logger not used - there is no need to declare it. Check all the comments and make sure it was done

**Comment by sLisnychyi** [comment]
changes has been committed.
@vkuchyn  pls review

**Pull request merged**
